all: newton SubsetsI SubsetsR

newton: NewtonRaphsonSqrt.cpp
	g++ --std=c++11 -o newtonSqrt NewtonRaphsonSqrt.cpp
	@echo 'Run ./newton NUMBER'
	@echo '-----------------'

SubsetsI: SubsetsI.cpp
	g++ --std=c++11 -o SubsetsI SubsetsI.cpp
	@echo 'Run ./SubsetsI ...'
	@echo '-----------------'

SubsetsR: SubsetsR.cpp
	g++ --std=c++11 -o SubsetsR SubsetsR.cpp
	@echo 'Run ./SubsetsR ...'
	@echo '-----------------'